# inherit common device tree
-include device/oppo/msm8974-common/BoardConfigCommon.mk

LOCAL_PATH := device/oppo/onyx

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := onyx
TARGET_OTA_ASSERT_DEVICE := onyx,ONYX

# Partition info
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216 
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1388314624
BOARD_USERDATAIMAGE_PARTITION_SIZE := 13271448576
BOARD_FLASH_BLOCK_SIZE := 131072

#dt.img
BOARD_MKBOOTIMG_ARGS := --dt device/oneplus/onyx/dt.img

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth

#Libinit - handle US, EU and CN
TARGET_INIT_VENDOR_LIB := libinit_onyx

# Recovery:Start

TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/configs/fstab.onyx
RECOVERY_SDCARD_ON_DATA := true
